[deploy]
startCommand = "npx prisma db push --accept-data-loss && node dist/main.js"
healthcheckPath = "/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
